dist: xenial
language: python
services: xvfb
addons:
  apt:
    update: true
    packages:
    # - ffmpeg
    - freeglut3-dev
    # - python3-gi
    # - python3-gi-cairo
    # - python-gst-1.0
matrix:
  include:
    - python: 2.7
    - python: 3.7
    - os: osx
      osx_image: xcode11
      language: minimal
before_install: pip install --upgrade pip flake8 pytest lektor
install: python setup.py install
before_script: flake8 . --count --exclude=./.*,*/future/* --select=E9,F63,F7,F82 --show-source --statistics || true
script: pytest --ignore=tests/base --ignore=tests/interactive --ignore=tests/integration/media --ignore=tests/integration/font --ignore=tests/integration/platform/test_linux_fontconfig.py
deploy:
  provider: script
  script: "lektor --project website build && lektor --project website deploy"
# after_success: coveralls
