name: PyTest

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14', 'pypy-3.10' ]
        backend-override: [ 'opengl', 'gl2', 'gles2', 'gles3']

    name: Python ${{ matrix.python-version }} Ubuntu ${{ matrix.backend-override }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          sudo apt-get install xvfb
      - name: Run tests
        env:
          PYGLET_BACKEND: ${{ matrix.backend-override }}
        run: |
          xvfb-run --auto-servernum  python3 -m pyglet.info
          xvfb-run --auto-servernum  pytest tests --ignore=tests/interactive

  osx:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14']
    name: Python ${{ matrix.python-version }} macOS
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run tests
        run: |
          python3 -m pyglet.info
          pytest tests --ignore=tests/interactive --ignore=tests/integration

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        backend-override: [ 'opengl', 'gl2', 'gles2' ]
    name: Python ${{ matrix.python-version }} Windows ${{ matrix.backend-override }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          release: false
          install: mingw-w64-x86_64-mesa
      - uses: ssciwr/setup-mesa-dist-win@v2
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run tests
        shell: pwsh
        env:
          PYGLET_BACKEND: ${{ matrix.backend-override }}
        run: |
          python3 -m pyglet.info
          pytest tests --ignore=tests/interactive

  headless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12', '3.13', '3.14', 'pypy-3.10' ]
        backend-override: [ 'opengl', 'gles2', 'gles3']

    name: Python ${{ matrix.python-version }} Ubuntu HEADLESS ${{ matrix.backend-override }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          sudo apt-get update
          sudo apt-get install --fix-missing libgl1-mesa-dev xvfb
      - name: Run tests
        env:
          PYGLET_BACKEND: ${{ matrix.backend-override }}
          PYGLET_HEADLESS: true
        run: |
          python3 -m pyglet.info
          pytest tests --ignore=tests/interactive
